// components/styles.js
import { StyleSheet } from "react-native";
import { useColorScheme } from "@/hooks/use-color-scheme";
import { Fonts } from "./theme";


export function useAppStyles() {
  const colorScheme = useColorScheme();

  const colors = {
    light: {
      background: "#F2F0EF",
      text: "#121212",
      textSecondary: "#666666",
      secondary: "#C9C8C7",
      primary: "#FFDE59",
      accent: "#4B7BEC",
      success: "#2ECC71",
      cardBackground: "#FFFFFF",
      inputBackground: "#E8E8E8",
      inputText: "#121212",
      placeholderText: "#999999",
      modalBackground: "#121212",
      modalContent: "#F2F0EF",
    },
    dark: {
      background: "#1F1B24",
      text: "#CFD8D7",
      textSecondary: "#999999",
      secondary: "#332940",
      primary: "#1A083E",
      accent: "#5B8BFC",
      success: "#3EDC81",
      cardBackground: "#2A2633",
      inputBackground: "#3A3644",
      inputText: "#CFD8D7",
      placeholderText: "#666666",
      modalBackground: "rgba(255,255,255,0.1)",
      modalContent: "#333333",
    },
  };

  const theme = colors[colorScheme ?? 'light'];

  const styles = StyleSheet.create({
    container: {
      flex: 1,
      alignItems: "flex-start",
      justifyContent: "center",
      backgroundColor: theme.background,
      color: theme.secondary,
      gap: 20,
      paddingHorizontal: 20,
    },
    title: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.text,
      fontFamily: Fonts.mono,
    },
    subtitle: {
      fontSize: 18,
      fontWeight: "normal",
      color: theme.text,
      fontFamily: Fonts.mono,
    },
    paragraph: {
      fontSize: 16,
      fontWeight: "300",
      color: theme.text,
      fontFamily: Fonts.sans,
    },
    separator: {
      marginVertical: 30,
      height: 1,
      width: "80%",
      backgroundColor: theme.text,
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
      width: "85%",
      maxWidth: 400,
      padding: 24,
      backgroundColor: theme.cardBackground,
      borderRadius: 16,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 10,
    },
    buttonStyle: {
      backgroundColor: theme.secondary,
      padding: 10,
      borderRadius: 10,
    },
    rowContainer: {
      flexDirection: "row",
      width: "100%",
      gap: 10,
      backgroundColor: theme.background,
    },
    flexButton: {
      flex: 1,            
      alignItems: "center",  
      justifyContent: "center", 
    },
    routineCard: {
      backgroundColor: theme.cardBackground,
      padding: 16,
      borderRadius: 12,
      width: "100%",
      marginVertical: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    exerciseCard: {
      backgroundColor: theme.secondary,
      padding: 12,
      borderRadius: 8,
      width: "100%",
      marginTop: 8,
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    stepContainer: {
        gap: 8,
        marginBottom: 8,
    },
    reactLogo: {
        height: 178,
        width: 290,
        bottom: 0,
        left: 0,
        position: 'absolute',
    },
    card: {
      backgroundColor: theme.cardBackground,
      borderRadius: 16,
      padding: 20,
      marginVertical: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    input: {
      backgroundColor: theme.inputBackground,
      color: theme.inputText,
      borderRadius: 20,
      padding: 12,
      fontSize: 16,
      fontFamily: Fonts.sans,
    },
    messageBubbleBot: {
      alignSelf: "flex-start",
      backgroundColor: theme.cardBackground,
      padding: 12,
      borderRadius: 16,
      borderBottomLeftRadius: 4,
      maxWidth: "75%",
      marginVertical: 4,
    },
    messageBubbleUser: {
      alignSelf: "flex-end",
      backgroundColor: theme.accent,
      padding: 12,
      borderRadius: 16,
      borderBottomRightRadius: 4,
      maxWidth: "75%",
      marginVertical: 4,
    },
    messageBubbleUserText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontFamily: Fonts.sans,
    },
    sendButton: {
      backgroundColor: theme.accent,
      padding: 12,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      width: 44,
      height: 44,
    },
    largeNumber: {
      fontSize: 48,
      fontWeight: "bold",
      color: theme.success,
      fontFamily: Fonts.mono,
      lineHeight: 56,
    },
    statCard: {
      backgroundColor: theme.cardBackground,
      borderRadius: 16,
      padding: 24,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    chartPlaceholder: {
      backgroundColor: theme.cardBackground,
      borderRadius: 12,
      padding: 20,
      height: 160,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    primaryButton: {
      backgroundColor: theme.accent,
      padding: 20,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: theme.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
    primaryButtonText: {
      color: "#FFFFFF",
      fontSize: 18,
      fontWeight: "bold",
      fontFamily: Fonts.sans,
    },
    subtleButton: {
      backgroundColor: theme.cardBackground,
      padding: 16,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.secondary,
    },
    themeContainer: {
      backgroundColor: theme.background,
      padding: 10,
      borderRadius: 10,
    },
    // Workout Modal Styles
    fullScreenModal: {
      flex: 1,
      backgroundColor: theme.background,
    },
    workoutModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.secondary,
      backgroundColor: theme.cardBackground,
    },
    workoutModalContent: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 16,
    },
    emptyWorkoutState: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 40,
    },
    addExerciseButton: {
      backgroundColor: theme.accent,
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
      marginVertical: 16,
    },
    addExerciseButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: Fonts.sans,
    },
    workoutExerciseCard: {
      backgroundColor: theme.cardBackground,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    exerciseHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    exerciseName: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.text,
      fontFamily: Fonts.mono,
      flex: 1,
    },
    removeExerciseButton: {
      padding: 8,
    },
    removeExerciseText: {
      color: '#FF4444',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: Fonts.sans,
    },
    setRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
      gap: 8,
    },
    setLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      fontFamily: Fonts.mono,
      width: 40,
    },
    setInput: {
      flex: 1,
      backgroundColor: theme.inputBackground,
      color: theme.inputText,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      fontFamily: Fonts.sans,
    },
    setInputLabel: {
      fontSize: 14,
      color: theme.textSecondary,
      fontFamily: Fonts.sans,
      marginBottom: 4,
    },
    setInputContainer: {
      flex: 1,
    },
    removeSetButton: {
      padding: 8,
    },
    removeSetText: {
      color: '#FF4444',
      fontSize: 20,
      fontWeight: 'bold',
    },
    addSetButton: {
      backgroundColor: theme.secondary,
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 8,
    },
    addSetButtonText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '600',
      fontFamily: Fonts.sans,
    },
    headerButton: {
      padding: 8,
    },
    headerButtonText: {
      fontSize: 16,
      fontWeight: '600',
      fontFamily: Fonts.sans,
    },
    closeButtonText: {
      color: theme.text,
    },
    finishButtonText: {
      color: theme.success,
    },
    // Exercise Picker Styles
    pickerModalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    pickerModalContent: {
      backgroundColor: theme.cardBackground,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      maxHeight: '80%',
      paddingTop: 20,
    },
    pickerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.secondary,
    },
    pickerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.text,
      fontFamily: Fonts.mono,
    },
    pickerList: {
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    categoryHeader: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.text,
      fontFamily: Fonts.mono,
      marginTop: 16,
      marginBottom: 8,
    },
    exercisePickerItem: {
      backgroundColor: theme.background,
      padding: 12,
      borderRadius: 8,
      marginBottom: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    exerciseVideoThumbnail: {
      width: 100,
      height: 100,
      borderRadius: 8,
      backgroundColor: '#000',
      overflow: 'hidden',
    },
    exercisePickerTextArea: {
      flex: 1,
      paddingVertical: 8,
    },
    exercisePickerText: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.text,
      fontFamily: Fonts.sans,
    },
    exercisePickerCategory: {
      fontSize: 14,
      color: theme.textSecondary,
      fontFamily: Fonts.sans,
      marginTop: 4,
    },
    // Finish Workout Dialog
    dialogOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    dialogContent: {
      backgroundColor: theme.cardBackground,
      borderRadius: 16,
      padding: 24,
      width: '85%',
      maxWidth: 400,
    },
    dialogTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.text,
      fontFamily: Fonts.mono,
      marginBottom: 16,
    },
    dialogInput: {
      backgroundColor: theme.inputBackground,
      color: theme.inputText,
      borderRadius: 12,
      padding: 14,
      fontSize: 16,
      fontFamily: Fonts.sans,
      marginBottom: 20,
    },
    dialogButtons: {
      flexDirection: 'row',
      gap: 12,
    },
    dialogButton: {
      flex: 1,
      padding: 14,
      borderRadius: 12,
      alignItems: 'center',
    },
    dialogButtonCancel: {
      backgroundColor: theme.secondary,
    },
    dialogButtonSave: {
      backgroundColor: theme.success,
    },
    dialogButtonText: {
      fontSize: 16,
      fontWeight: '600',
      fontFamily: Fonts.sans,
    },
    dialogButtonTextCancel: {
      color: theme.text,
    },
    dialogButtonTextSave: {
      color: '#FFFFFF',
    },
  });

  return styles;
}
